routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => 'auth'], function() {
    Route::get('/', 'HomeController@index');
    Route::group(['prefix' => 'user-administrations', 'namespace' => 'UserAdministrations'], function() {
        Route::resource('users', 'UsersController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('roles', 'RolesController');
    });
});

Route::resource('project','Project\Project');
Route::resource('endpoint','Endpoint\EndPoint');

resources/views/mockupsever.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index Page</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">  
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">  
    <script  data-src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>  
  </head>
  <body>
    <div class="row">
      <div class="col-sm-12">
          <div class="card">
            <div class="card-block">
              <a href="{{ route('project.index') }}" class="btn btn-success pull-left">Project</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
          <div class="card">
            <div class="card-block">
              <a href="" class="btn btn-success pull-left">Endpoint</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>